name 'chef-rails'
maintainer 'Nghiem Ba Hieu'
maintainer_email 'hi3unb@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures and deploys RoR4'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)

supports 'ubuntu', '~> 16.04'

depends 'apt', '~> 6.1.4'
depends 'build-essential', '~> 8.0.4'
depends 'ruby_rbenv', '~> 2.0.6'
depends 'ruby_build', '~> 1.1.0'
depends 'mysql', '~> 8.5.1'
depends 'nginx', '~> 7.0.2'
depends 'postfix', '~> 5.2.1'
depends 'sudo', '~> 4.0.0'
depends 'users', '~> 4.0.3'
depends 'imagemagick', '~> 0.2.3'
depends 'poise-service', '~> 1.5.2'
# Vendor cookbooks
depends 'packages'
depends 'rails'
depends 'ssh_deploy_keys'
depends 'backups'
depends 'sysadmins'
